package com.yan.dao.mapper.logging;

import com.yan.dao.model.logging.LoggingEventException;
import com.yan.dao.model.logging.LoggingEventExceptionExample;
import com.yan.dao.model.logging.LoggingEventExceptionKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LoggingEventExceptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_exception
     *
     * @mbg.generated Fri Sep 15 16:14:57 CST 2017
     */
    long countByExample(LoggingEventExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_exception
     *
     * @mbg.generated Fri Sep 15 16:14:57 CST 2017
     */
    int deleteByExample(LoggingEventExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_exception
     *
     * @mbg.generated Fri Sep 15 16:14:57 CST 2017
     */
    int deleteByPrimaryKey(LoggingEventExceptionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_exception
     *
     * @mbg.generated Fri Sep 15 16:14:57 CST 2017
     */
    int insert(LoggingEventException record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_exception
     *
     * @mbg.generated Fri Sep 15 16:14:57 CST 2017
     */
    int insertSelective(LoggingEventException record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_exception
     *
     * @mbg.generated Fri Sep 15 16:14:57 CST 2017
     */
    List<LoggingEventException> selectByExample(LoggingEventExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_exception
     *
     * @mbg.generated Fri Sep 15 16:14:57 CST 2017
     */
    LoggingEventException selectByPrimaryKey(LoggingEventExceptionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_exception
     *
     * @mbg.generated Fri Sep 15 16:14:57 CST 2017
     */
    int updateByExampleSelective(@Param("record") LoggingEventException record, @Param("example") LoggingEventExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_exception
     *
     * @mbg.generated Fri Sep 15 16:14:57 CST 2017
     */
    int updateByExample(@Param("record") LoggingEventException record, @Param("example") LoggingEventExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_exception
     *
     * @mbg.generated Fri Sep 15 16:14:57 CST 2017
     */
    int updateByPrimaryKeySelective(LoggingEventException record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_exception
     *
     * @mbg.generated Fri Sep 15 16:14:57 CST 2017
     */
    int updateByPrimaryKey(LoggingEventException record);
}