package com.yan.dao.model.role;

import java.io.Serializable;

public class RoleMenuRel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE_MENU_REL.REL_ID
     *
     * @mbg.generated Wed Feb 07 16:03:39 CST 2018
     */
    /**
     * 关系ID（主键）
     *
     * @mbg.generated Wed Feb 07 16:03:39 CST 2018
     */
    private String relId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE_MENU_REL.ROLE_ID
     *
     * @mbg.generated Wed Feb 07 16:03:39 CST 2018
     */
    /**
     * 角色ID
     *
     * @mbg.generated Wed Feb 07 16:03:39 CST 2018
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE_MENU_REL.MENU_ID
     *
     * @mbg.generated Wed Feb 07 16:03:39 CST 2018
     */
    /**
     * 菜单资源ID
     *
     * @mbg.generated Wed Feb 07 16:03:39 CST 2018
     */
    private String menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ROLE_MENU_REL
     *
     * @mbg.generated Wed Feb 07 16:03:39 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE_MENU_REL.REL_ID
     *
     * @return the value of ROLE_MENU_REL.REL_ID
     *
     * @mbg.generated Wed Feb 07 16:03:39 CST 2018
     */
    public String getRelId() {
        return relId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE_MENU_REL.REL_ID
     *
     * @param relId the value for ROLE_MENU_REL.REL_ID
     *
     * @mbg.generated Wed Feb 07 16:03:39 CST 2018
     */
    public void setRelId(String relId) {
        this.relId = relId == null ? null : relId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE_MENU_REL.ROLE_ID
     *
     * @return the value of ROLE_MENU_REL.ROLE_ID
     *
     * @mbg.generated Wed Feb 07 16:03:39 CST 2018
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE_MENU_REL.ROLE_ID
     *
     * @param roleId the value for ROLE_MENU_REL.ROLE_ID
     *
     * @mbg.generated Wed Feb 07 16:03:39 CST 2018
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE_MENU_REL.MENU_ID
     *
     * @return the value of ROLE_MENU_REL.MENU_ID
     *
     * @mbg.generated Wed Feb 07 16:03:39 CST 2018
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE_MENU_REL.MENU_ID
     *
     * @param menuId the value for ROLE_MENU_REL.MENU_ID
     *
     * @mbg.generated Wed Feb 07 16:03:39 CST 2018
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_MENU_REL
     *
     * @mbg.generated Wed Feb 07 16:03:39 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", relId=").append(relId);
        sb.append(", roleId=").append(roleId);
        sb.append(", menuId=").append(menuId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}