package com.yan.dao.model.role;

import java.io.Serializable;

public class SysRole implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.ROLE_ID
     *
     * @mbg.generated Tue Sep 19 11:14:34 CST 2017
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.ROLE_PID
     *
     * @mbg.generated Tue Sep 19 11:14:34 CST 2017
     */
    private String rolePid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.ROLE_NAME
     *
     * @mbg.generated Tue Sep 19 11:14:34 CST 2017
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.ROLE_INDEX
     *
     * @mbg.generated Tue Sep 19 11:14:34 CST 2017
     */
    private Integer roleIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.ROLE_TYPE
     *
     * @mbg.generated Tue Sep 19 11:14:34 CST 2017
     */
    private String roleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.ROLE_LEVEL
     *
     * @mbg.generated Tue Sep 19 11:14:34 CST 2017
     */
    private Integer roleLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.ROLE_VALID
     *
     * @mbg.generated Tue Sep 19 11:14:34 CST 2017
     */
    private Boolean roleValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYS_ROLE
     *
     * @mbg.generated Tue Sep 19 11:14:34 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.ROLE_ID
     *
     * @return the value of SYS_ROLE.ROLE_ID
     *
     * @mbg.generated Tue Sep 19 11:14:34 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.ROLE_ID
     *
     * @param roleId the value for SYS_ROLE.ROLE_ID
     *
     * @mbg.generated Tue Sep 19 11:14:34 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.ROLE_PID
     *
     * @return the value of SYS_ROLE.ROLE_PID
     *
     * @mbg.generated Tue Sep 19 11:14:34 CST 2017
     */
    public String getRolePid() {
        return rolePid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.ROLE_PID
     *
     * @param rolePid the value for SYS_ROLE.ROLE_PID
     *
     * @mbg.generated Tue Sep 19 11:14:34 CST 2017
     */
    public void setRolePid(String rolePid) {
        this.rolePid = rolePid == null ? null : rolePid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.ROLE_NAME
     *
     * @return the value of SYS_ROLE.ROLE_NAME
     *
     * @mbg.generated Tue Sep 19 11:14:34 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.ROLE_NAME
     *
     * @param roleName the value for SYS_ROLE.ROLE_NAME
     *
     * @mbg.generated Tue Sep 19 11:14:34 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.ROLE_INDEX
     *
     * @return the value of SYS_ROLE.ROLE_INDEX
     *
     * @mbg.generated Tue Sep 19 11:14:34 CST 2017
     */
    public Integer getRoleIndex() {
        return roleIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.ROLE_INDEX
     *
     * @param roleIndex the value for SYS_ROLE.ROLE_INDEX
     *
     * @mbg.generated Tue Sep 19 11:14:34 CST 2017
     */
    public void setRoleIndex(Integer roleIndex) {
        this.roleIndex = roleIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.ROLE_TYPE
     *
     * @return the value of SYS_ROLE.ROLE_TYPE
     *
     * @mbg.generated Tue Sep 19 11:14:34 CST 2017
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.ROLE_TYPE
     *
     * @param roleType the value for SYS_ROLE.ROLE_TYPE
     *
     * @mbg.generated Tue Sep 19 11:14:34 CST 2017
     */
    public void setRoleType(String roleType) {
        this.roleType = roleType == null ? null : roleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.ROLE_LEVEL
     *
     * @return the value of SYS_ROLE.ROLE_LEVEL
     *
     * @mbg.generated Tue Sep 19 11:14:34 CST 2017
     */
    public Integer getRoleLevel() {
        return roleLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.ROLE_LEVEL
     *
     * @param roleLevel the value for SYS_ROLE.ROLE_LEVEL
     *
     * @mbg.generated Tue Sep 19 11:14:34 CST 2017
     */
    public void setRoleLevel(Integer roleLevel) {
        this.roleLevel = roleLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.ROLE_VALID
     *
     * @return the value of SYS_ROLE.ROLE_VALID
     *
     * @mbg.generated Tue Sep 19 11:14:34 CST 2017
     */
    public Boolean getRoleValid() {
        return roleValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.ROLE_VALID
     *
     * @param roleValid the value for SYS_ROLE.ROLE_VALID
     *
     * @mbg.generated Tue Sep 19 11:14:34 CST 2017
     */
    public void setRoleValid(Boolean roleValid) {
        this.roleValid = roleValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE
     *
     * @mbg.generated Tue Sep 19 11:14:34 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleId=").append(roleId);
        sb.append(", rolePid=").append(rolePid);
        sb.append(", roleName=").append(roleName);
        sb.append(", roleIndex=").append(roleIndex);
        sb.append(", roleType=").append(roleType);
        sb.append(", roleLevel=").append(roleLevel);
        sb.append(", roleValid=").append(roleValid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}