package com.yan.dao.model.logging;

import java.io.Serializable;

public class LoggingEventPropertyKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logging_event_property.event_id
     *
     * @mbg.generated Wed Feb 07 16:05:59 CST 2018
     */
    private Long eventId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logging_event_property.mapped_key
     *
     * @mbg.generated Wed Feb 07 16:05:59 CST 2018
     */
    private String mappedKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table logging_event_property
     *
     * @mbg.generated Wed Feb 07 16:05:59 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logging_event_property.event_id
     *
     * @return the value of logging_event_property.event_id
     *
     * @mbg.generated Wed Feb 07 16:05:59 CST 2018
     */
    public Long getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logging_event_property.event_id
     *
     * @param eventId the value for logging_event_property.event_id
     *
     * @mbg.generated Wed Feb 07 16:05:59 CST 2018
     */
    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logging_event_property.mapped_key
     *
     * @return the value of logging_event_property.mapped_key
     *
     * @mbg.generated Wed Feb 07 16:05:59 CST 2018
     */
    public String getMappedKey() {
        return mappedKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logging_event_property.mapped_key
     *
     * @param mappedKey the value for logging_event_property.mapped_key
     *
     * @mbg.generated Wed Feb 07 16:05:59 CST 2018
     */
    public void setMappedKey(String mappedKey) {
        this.mappedKey = mappedKey == null ? null : mappedKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_property
     *
     * @mbg.generated Wed Feb 07 16:05:59 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", eventId=").append(eventId);
        sb.append(", mappedKey=").append(mappedKey);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}