package com.yan.dao.model.logging;

import java.util.ArrayList;
import java.util.List;

public class LoggingEventPropertyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table logging_event_property
     *
     * @mbg.generated Fri Sep 15 16:14:13 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table logging_event_property
     *
     * @mbg.generated Fri Sep 15 16:14:13 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table logging_event_property
     *
     * @mbg.generated Fri Sep 15 16:14:13 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_property
     *
     * @mbg.generated Fri Sep 15 16:14:13 CST 2017
     */
    public LoggingEventPropertyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_property
     *
     * @mbg.generated Fri Sep 15 16:14:13 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_property
     *
     * @mbg.generated Fri Sep 15 16:14:13 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_property
     *
     * @mbg.generated Fri Sep 15 16:14:13 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_property
     *
     * @mbg.generated Fri Sep 15 16:14:13 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_property
     *
     * @mbg.generated Fri Sep 15 16:14:13 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_property
     *
     * @mbg.generated Fri Sep 15 16:14:13 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_property
     *
     * @mbg.generated Fri Sep 15 16:14:13 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_property
     *
     * @mbg.generated Fri Sep 15 16:14:13 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_property
     *
     * @mbg.generated Fri Sep 15 16:14:13 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_property
     *
     * @mbg.generated Fri Sep 15 16:14:13 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table logging_event_property
     *
     * @mbg.generated Fri Sep 15 16:14:13 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEventIdIsNull() {
            addCriterion("event_id is null");
            return (Criteria) this;
        }

        public Criteria andEventIdIsNotNull() {
            addCriterion("event_id is not null");
            return (Criteria) this;
        }

        public Criteria andEventIdEqualTo(Long value) {
            addCriterion("event_id =", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdNotEqualTo(Long value) {
            addCriterion("event_id <>", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdGreaterThan(Long value) {
            addCriterion("event_id >", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdGreaterThanOrEqualTo(Long value) {
            addCriterion("event_id >=", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdLessThan(Long value) {
            addCriterion("event_id <", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdLessThanOrEqualTo(Long value) {
            addCriterion("event_id <=", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdIn(List<Long> values) {
            addCriterion("event_id in", values, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdNotIn(List<Long> values) {
            addCriterion("event_id not in", values, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdBetween(Long value1, Long value2) {
            addCriterion("event_id between", value1, value2, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdNotBetween(Long value1, Long value2) {
            addCriterion("event_id not between", value1, value2, "eventId");
            return (Criteria) this;
        }

        public Criteria andMappedKeyIsNull() {
            addCriterion("mapped_key is null");
            return (Criteria) this;
        }

        public Criteria andMappedKeyIsNotNull() {
            addCriterion("mapped_key is not null");
            return (Criteria) this;
        }

        public Criteria andMappedKeyEqualTo(String value) {
            addCriterion("mapped_key =", value, "mappedKey");
            return (Criteria) this;
        }

        public Criteria andMappedKeyNotEqualTo(String value) {
            addCriterion("mapped_key <>", value, "mappedKey");
            return (Criteria) this;
        }

        public Criteria andMappedKeyGreaterThan(String value) {
            addCriterion("mapped_key >", value, "mappedKey");
            return (Criteria) this;
        }

        public Criteria andMappedKeyGreaterThanOrEqualTo(String value) {
            addCriterion("mapped_key >=", value, "mappedKey");
            return (Criteria) this;
        }

        public Criteria andMappedKeyLessThan(String value) {
            addCriterion("mapped_key <", value, "mappedKey");
            return (Criteria) this;
        }

        public Criteria andMappedKeyLessThanOrEqualTo(String value) {
            addCriterion("mapped_key <=", value, "mappedKey");
            return (Criteria) this;
        }

        public Criteria andMappedKeyLike(String value) {
            addCriterion("mapped_key like", value, "mappedKey");
            return (Criteria) this;
        }

        public Criteria andMappedKeyNotLike(String value) {
            addCriterion("mapped_key not like", value, "mappedKey");
            return (Criteria) this;
        }

        public Criteria andMappedKeyIn(List<String> values) {
            addCriterion("mapped_key in", values, "mappedKey");
            return (Criteria) this;
        }

        public Criteria andMappedKeyNotIn(List<String> values) {
            addCriterion("mapped_key not in", values, "mappedKey");
            return (Criteria) this;
        }

        public Criteria andMappedKeyBetween(String value1, String value2) {
            addCriterion("mapped_key between", value1, value2, "mappedKey");
            return (Criteria) this;
        }

        public Criteria andMappedKeyNotBetween(String value1, String value2) {
            addCriterion("mapped_key not between", value1, value2, "mappedKey");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table logging_event_property
     *
     * @mbg.generated do_not_delete_during_merge Fri Sep 15 16:14:13 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table logging_event_property
     *
     * @mbg.generated Fri Sep 15 16:14:13 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}