package com.yan.dao.model.logging;

import java.io.Serializable;

public class LoggingEventException extends LoggingEventExceptionKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logging_event_exception.trace_line
     *
     * @mbg.generated Fri Sep 15 16:14:57 CST 2017
     */
    private String traceLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table logging_event_exception
     *
     * @mbg.generated Fri Sep 15 16:14:57 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logging_event_exception.trace_line
     *
     * @return the value of logging_event_exception.trace_line
     *
     * @mbg.generated Fri Sep 15 16:14:57 CST 2017
     */
    public String getTraceLine() {
        return traceLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logging_event_exception.trace_line
     *
     * @param traceLine the value for logging_event_exception.trace_line
     *
     * @mbg.generated Fri Sep 15 16:14:57 CST 2017
     */
    public void setTraceLine(String traceLine) {
        this.traceLine = traceLine == null ? null : traceLine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logging_event_exception
     *
     * @mbg.generated Fri Sep 15 16:14:57 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", traceLine=").append(traceLine);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}